version: "3.7"
services:
  backend:
    build:
      context: .
    ports:
      - 8090:8090
    environment:
      - PORT=8090
      - DBURL=localhost
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=todo
      - DBPORT=3306
